# Generated by Django 3.1.3 on 2020-11-25 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('nearby', models.TextField(max_length=300)),
                ('type', models.IntegerField()),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('private_bathroom', models.BooleanField()),
                ('co_nonglanh', models.BooleanField()),
                ('kitchen', models.IntegerField()),
                ('air_conditional', models.BooleanField()),
                ('ban_cong', models.BooleanField()),
                ('service_charge', models.TextField(max_length=100)),
                ('other_ultily', models.TextField()),
                ('longevity', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(364)])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
