# Generated by Django 3.1.3 on 2020-12-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms'),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
