# Generated by Django 3.1.3 on 2020-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20201208_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='post',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='images',
            field=models.FileField(upload_to='media/images/rooms/'),
        ),
    ]
