# Generated by Django 3.1.3 on 2020-12-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20201222_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='name',
            new_name='name_type',
        ),
    ]
