# Generated by Django 3.1.3 on 2020-12-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20201222_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amount_of_room_intype',
            field=models.IntegerField(default=0),
        ),
    ]
