# Generated by Django 3.1.3 on 2020-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_roomtype_amount_of_room_intype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='name_type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='amount_of_room_intype',
            field=models.IntegerField(),
        ),
    ]
