# Generated by Django 3.1.3 on 2020-12-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_caredroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
