# Generated by Django 3.1.3 on 2020-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='kitchen',
            field=models.IntegerField(choices=[(0, 'Bếp riêng'), (1, 'Chung'), (2, 'Không nấu ăn')], default=0),
        ),
    ]
