# Generated by Django 3.1.3 on 2020-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_auto_20201226_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pro_city_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='pro_city_pa_id',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
