# Generated by Django 3.1.3 on 2020-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_auto_20201226_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
