# Generated by Django 3.1.3 on 2020-12-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_room_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='viewed',
            field=models.IntegerField(default=24),
        ),
    ]
