# Generated by Django 3.1.3 on 2020-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201208_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneruser',
            name='full_name',
            field=models.CharField(default='', max_length=120, verbose_name='Ho va ten'),
        ),
    ]
