# Generated by Django 3.1.3 on 2020-12-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_owneruser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneruser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
