# Generated by Django 3.1.3 on 2020-12-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_owneruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneruser',
            name='is_owner',
            field=models.IntegerField(choices=[(0, 'Người thuê trọ'), (1, 'Chủ nhà trọ')], default=0, verbose_name='Ban la'),
        ),
    ]
